In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from nltk.cluster import KMeansClusterer
from scipy.cluster.vq import kmeans

In [3]:
book_df = pd.read_csv('data/book_review_data.csv')
book_df.head(20)

,Unnamed: 0,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
0,0,2,"stockton, california, usa",18.0000,0195153448,0,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science'],stockton,california,usa
1,1,8,"timmins, ontario, canada",34.7439,0002005018,5,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],timmins,ontario,canada
2,2,11400,"ottawa, ontario, canada",49.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
3,3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
4,4,41385,"sudbury, ontario, canada",34.7439,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],sudbury,ontario,canada
5,5,67544,"toronto, ontario, canada",30.0000,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],toronto,ontario,canada
6,6,85526,"victoria, british columbia, canada",36.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],victoria,british columbia,canada
7,7,96054,"ottawa, ontario, canada",29.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
8,8,116866,"ottawa, ,",34.7439,0002005018,9,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,",",NaN
9,9,123629,"kingston, ontario, canada",34.7439,0002005018,9,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],kingston,ontario,canada
10,10,177458,"ottawa, ontario, canada",29.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
11,11,200273,"comber, ontario, canada",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],comber,ontario,canada
12,12,210926,"guelph, ontario, canada",34.7439,0002005018,9,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],guelph,ontario,canada
13,13,219008,"halifax, nova scotia, canada",60.0000,0002005018,7,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],halifax,nova scotia,canada
14,14,263325,"fredericton, new brunswick, canada",27.0000,0002005018,6,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],fredericton,new brunswick,canada
15,15,8,"timmins, ontario, canada",34.7439,0060973129,0,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,"Here, for the first time in paperback, is an o...",en,['1940-1949'],timmins,ontario,canada
16,16,2954,"wichita, kansas, usa",71.0000,0060973129,8,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,"Here, for the first time in paperback, is an o...",en,['1940-1949'],wichita,kansas,usa
17,17,152827,"ottawa, ontario, canada",40.0000,0060973129,7,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,"Here, for the first time in paperback, is an o...",en,['1940-1949'],ottawa,ontario,canada
18,18,8,"timmins, ontario, canada",34.7439,0374157065,0,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,"Describes the great flu epidemic of 1918, an o...",en,['Medical'],timmins,ontario,canada
19,19,35704,"kansas city, missouri, usa",53.0000,0374157065,6,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,"Describes the great flu epidemic of 1918, an o...",en,['Medical'],kansas city,missouri,usa

In [4]:
book_df = book_df[['user_id','age','rating','book_title','book_author','year_of_publication','img_m','Summary','Category','country']]
book_df.head(100)

,user_id,age,rating,book_title,book_author,year_of_publication,img_m,Summary,Category,country
0,2,18.0000,0,Classical Mythology,Mark P. O. Morford,2002.0,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,['Social Science'],usa
1,8,34.7439,5,Clara Callan,Richard Bruce Wright,2001.0,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",['Actresses'],canada
2,11400,49.0000,0,Clara Callan,Richard Bruce Wright,2001.0,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",['Actresses'],canada
3,11676,34.7439,8,Clara Callan,Richard Bruce Wright,2001.0,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",['Actresses'],NaN
4,41385,34.7439,0,Clara Callan,Richard Bruce Wright,2001.0,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",['Actresses'],canada
...,...,...,...,...,...,...,...,...,...,...
95,8,34.7439,7,Goodbye to the Buttermilk Sky,Julia Oliver,1994.0,http://images.amazon.com/images/P/1881320189.0...,A beautifully narrated novel of time and place...,['Fiction'],canada
96,35826,34.7439,0,Goodbye to the Buttermilk Sky,Julia Oliver,1994.0,http://images.amazon.com/images/P/1881320189.0...,A beautifully narrated novel of time and place...,['Fiction'],usa
97,226745,38.0000,7,Goodbye to the Buttermilk Sky,Julia Oliver,1994.0,http://images.amazon.com/images/P/1881320189.0...,A beautifully narrated novel of time and place...,['Fiction'],NaN
98,9,34.7439,0,The Testament,John Grisham,1999.0,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",['Fiction'],usa
99,243,34.7439,0,The Testament,John Grisham,1999.0,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",['Fiction'],usa

In [5]:
book_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031175 entries, 0 to 1031174
Data columns (total 10 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   user_id              1031175 non-null  int64
 1   age                  1031175 non-null  float64
 2   rating               1031175 non-null  int64
 3   book_title           1031175 non-null  object
 4   book_author          1031174 non-null  object
 5   year_of_publication  1031175 non-null  float64
 6   img_m                1031175 non-null  object
 7   Summary              1031175 non-null  object
 8   Category             1031175 non-null  object
 9   country              995801 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 78.7+ MB

In [6]:
book_df.describe()

            user_id           age        rating  year_of_publication
count  1.031175e+06  1.031175e+06  1.031175e+06         1.031175e+06
mean   1.405944e+05  3.642902e+01  2.839022e+00         1.995283e+03
std    8.052444e+04  1.035354e+01  3.854149e+00         7.309340e+00
min    2.000000e+00  5.000000e+00  0.000000e+00         1.376000e+03
25%    7.041500e+04  3.100000e+01  0.000000e+00         1.992000e+03
50%    1.412100e+05  3.474390e+01  0.000000e+00         1.997000e+03
75%    2.114260e+05  4.100000e+01  7.000000e+00         2.001000e+03
max    2.788540e+05  9.900000e+01  1.000000e+01         2.008000e+03

In [7]:
# 0점을 준 사람
rating_zero = book_df[book_df['rating']==0]['user_id']
rating_zero

0               2
2           11400
4           41385
6           85526
7           96054
            ...
1031165    278843
1031166    278849
1031167    278851
1031168    278851
1031170    278851
Name: user_id, Length: 647323, dtype: int64

In [8]:

# # 0점만 준 사람
# only_zero_rating = book_df.groupby('user_id').filter(lambda x:x['rating'].nunique()==1 and x['rating'].iloc[0]==0)
# only_zero_rating

In [9]:
# # 사용자별로 rating
# user_rating = book_df.groupby('user_id')['rating'].nunique()
# user_rating

In [10]:
book_df=pd.read_csv('data/book_review_data.csv')

In [11]:
# 1) 필요한 컬럼 도출
# 2) 형변환 (float > int)

book_df=book_df[['user_id',"age","rating","book_title",'book_author','year_of_publication','img_m','Summary','Category','country']]
book_df[['age',"year_of_publication"]]=book_df[['age',"year_of_publication"]].astype(int)

In [12]:
# 최소 평가 개수 ( 평가가 30개보다 많은 책만 추출 )
counts=book_df['book_title'].value_counts()
title = counts[counts > 30].index
book_filter_df = book_df[book_df['book_title'].isin(title)]
book_filter_df.value_counts()

user_id  age  rating  book_title                                                                                 book_author       year_of_publication  img_m                                                         Summary                                                                                                                                                                                                                                                   Category     country
8        34   0       A Second Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series)              Jack Canfield     1998                 http://images.amazon.com/images/P/1558746218.01.MZZZZZZZ.jpg  9                                                                                                                                                                                                                                                         9            canada     1
187266   66   5       Covenant                                                                                   James Michener    1982                 http://images.amazon.com/images/P/0449244741.01.MZZZZZZZ.jpg  9                                                                                                                                                                                                                                                         9            usa        1
187277   34   0       Gentle Rogue (Malory Novels (Paperback))                                                   Johanna Lindsey   1990                 http://images.amazon.com/images/P/0380753022.01.MZZZZZZZ.jpg  Heartsick and desperate to return home to America, Georgina Anderson\nboards the Maiden Anne disguised as a cabin boy, never dreaming\nshe&#39;ll be forced into intimate servitude at the whim of the\nship&#39;s irrepressible captain, James Mallory.  ['Fiction']  canada     1
187274   34   7       The Reader                                                                                 Bernhard Schlink  1999                 http://images.amazon.com/images/P/0375707972.01.MZZZZZZZ.jpg  At the age of fifteen, Michael Berg falls in love with a woman who\ndisappears, and while observing a trial as a law student years later,\nhe is shocked to discover the same woman as the defendant in a\nhorrible crime                                 ['Fiction']  usa        1
              6       A Patchwork Planet (Ballantine Reader's Circle)                                            Anne Tyler        1999                 http://images.amazon.com/images/P/0449003981.01.MZZZZZZZ.jpg  In her fourteenth novel, a New York Times best-seller, the Pulitzer\nPrize-winning novelist follows a loveable loser and occasional thief\nas he tries to reform under the influence of a decent young woman.\nReprint.                                   ['Fiction']  usa        1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
95359    33   0       The BFG                                                                                    Roald Dahl        1982                 http://images.amazon.com/images/P/0590975005.01.MZZZZZZZ.jpg  Kidsnatched from her orphange by a BFG (Big Friendly Giant), who\nspends his life blowing happy dreams to children, Sophie concocts with\nhim a plan to save the world from nine other man-gobbling cannybull\ngiants.                                    ['Dreams']   usa        1
                      The Amazing Adventures of Kavalier & Clay                                                  Michael Chabon    2001                 http://images.amazon.com/images/P/0312282990.01.MZZZZZZZ.jpg  9                                                                                                                                                                                                                                                         9            usa        1
                      The All-True Travels and Adventures of Lidie Newton: A Novel (Ballantine Reader's Circle)  Jane Smiley       1999                 http://images.amazon.com/images/P/0449910830.01.MZZZZZZZ.jpg  Offers the pre-Civil War memoirs of an abolitionist who in 1855 enters\nthe fray between Kansas free-staters and slave-holding Missourians                                                                                                                ['Fiction']  usa        1
                      Tears of the Moon (Irish Trilogy)                                                          Nora Roberts      2000                 http://images.amazon.com/images/P/0515128546.01.MZZZZZZZ.jpg  Only when Shawn Gallagher mixes his music with magic is he able to see\nhow much tomboy Brenna O&#39;Toole cares about him.                                                                                                                               ['Fiction']  usa        1
278854   34   8       Ashes to Ashes                                                                             TAMI HOAG         2000                 http://images.amazon.com/images/P/0553579606.01.MZZZZZZZ.jpg  In the darkness a match is struck. Not for heat, not for light...but\nto ignite the fire of a killer. He leaves nothing behind but\nashes...and the ice-cold certainty that he will strike again.                                                         ['Fiction']  usa        1
Name: count, Length: 352491, dtype: int64

In [13]:
# 최소 평가 개수 ( 평가가 20개보다 많은 사용자만 추출 )
counts=book_df["user_id"].value_counts()
user_id_=counts[counts>20].index
book_filter_df = book_filter_df[book_filter_df['user_id'].isin(user_id_)]

In [14]:
# 무의미한 0점 평가 제거
rating_zero=book_filter_df[book_filter_df['rating']==0].index
book_filter_df.drop(rating_zero, axis=0, inplace=True)
book_filter_df

,user_id,age,rating,book_title,book_author,year_of_publication,img_m,Summary,Category,country
31,11676,34,9,The Kitchen God's Wife,Amy Tan,1991,http://images.amazon.com/images/P/0399135782.0...,A Chinese immigrant who is convinced she is dy...,['Fiction'],NaN
32,29526,26,9,The Kitchen God's Wife,Amy Tan,1991,http://images.amazon.com/images/P/0399135782.0...,A Chinese immigrant who is convinced she is dy...,['Fiction'],usa
34,46398,37,9,The Kitchen God's Wife,Amy Tan,1991,http://images.amazon.com/images/P/0399135782.0...,A Chinese immigrant who is convinced she is dy...,['Fiction'],usa
36,49635,34,9,The Kitchen God's Wife,Amy Tan,1991,http://images.amazon.com/images/P/0399135782.0...,A Chinese immigrant who is convinced she is dy...,['Fiction'],usa
42,148712,34,10,The Kitchen God's Wife,Amy Tan,1991,http://images.amazon.com/images/P/0399135782.0...,A Chinese immigrant who is convinced she is dy...,['Fiction'],usa
...,...,...,...,...,...,...,...,...,...,...
1027926,273197,55,8,Island,Thomas Perry,1989,http://images.amazon.com/images/P/0380706636.0...,"A husband-and-wife con team, a soldier of fort...",['Fiction'],usa
1028086,273718,32,6,Pearl,Anon,1999,http://images.amazon.com/images/P/1853266094.0...,9,9,united kingdom
1028386,274061,26,10,Fever,Elizabeth Lowell,1997,http://images.amazon.com/images/P/1551663147.0...,"Fever by Elizabeth Lowell released on Dec 25, ...",['Utah'],usa
1029323,275970,46,9,Me Talk Pretty One Day,David Sedaris,2001,http://images.amazon.com/images/P/1586210661.0...,9,9,usa
1029690,277157,70,5,Saving Faith,DAVID BALDACCI,2000,http://images.amazon.com/images/P/0375727981.0...,"In a novel of Washington insider intrigue, inf...",['Fiction'],usa

In [15]:
# book_filter_df['Category'].value_counts()

In [16]:
# 카테고리 소문자로 만들기 / 앞뒤 공백 제거/ 중백 공백 표준화 / 특수문자 제거

# book_filter_df['Category'] == book_filter_df['Category'].str.lower()
# book_filter_df['Category']

def preprocess_category(text):
    return(
        text
        .str.lower()
        .str.strip()  
        .str.replace(r'\s+', ' ', regex=True)
        .str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
    )

book_filter_df['Category']=preprocess_category(book_filter_df['Category'])

book_filter_df['Category'].value_counts()

Category
fiction                     42800
9                           29508
juvenile fiction             3391
biography  autobiography     2021
humor                         776
                            ...
brothers                        1
government investigators        1
children of presidents          1
israel                          1
utah                            1
Name: count, Length: 377, dtype: int64

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
import pandas as pd

# 1. CountVectorizer 객체 생성 및 데이터 벡터화
count_vectorizer = CountVectorizer()
category_vecs = count_vectorizer.fit_transform(book_filter_df['Category'])
print(category_vecs.shape)
print(count_vectorizer.vocabulary_) # (365778, 1092) (카테고리수, 단어수)
category_vec_vocab = pd.DataFrame(count_vectorizer.vocabulary_,index=['index']).T
category_vec_vocab

(85479, 506)
{'fiction': 260, 'cooking': 184, 'history': 293, 'humor': 304, 'conduct': 180, 'of': 404, 'life': 351, 'americans': 37, 'humorous': 305, 'stories': 473, 'diary': 217, 'juvenile': 333, 'biography': 93, 'autobiography': 76, 'selfhelp': 459, 'adolescence': 14, 'dune': 231, 'imaginary': 310, 'place': 422, 'animals': 45, 'great': 285, 'britain': 112, 'london': 356, 'england': 238, 'arctic': 54, 'regions': 441, 'aerospace': 22, 'engineers': 237, 'computers': 179, 'nature': 392, 'businessmen': 121, 'social': 464, 'science': 456, 'literary': 354, 'collections': 167, 'adulteresses': 17, 'business': 120, 'economics': 234, 'rapture': 435, 'christian': 154, 'eschatology': 245, 'detective': 213, 'and': 42, 'mystery': 389, 'fantasy': 256, 'horror': 298, 'tales': 478, 'feminists': 259, 'political': 426, 'philosophy': 418, 'community': 176, 'colleges': 168, 'artists': 62, 'courtship': 193, 'ryan': 453, 'jack': 326, 'fictitious': 262, 'character': 142, 'journalists': 332, 'body': 98, 'mind': 376, 'spirit': 469, 'trials': 487, 'murder': 386, 'continental': 183, 'european': 248, 'fictional': 261, 'works': 503, 'by': 123, 'one': 406, 'author': 74, 'american': 36, 'literature': 355, 'nonfiction': 400, 'authors': 75, 'california': 124, 'colombian': 171, 'poetry': 424, 'bildungsromans': 90, 'monastic': 380, 'religious': 445, 'british': 113, 'irish': 322, 'atomic': 67, 'bomb': 99, 'dogs': 223, 'alchemists': 30, 'geishas': 278, 'christmas': 156, 'fairies': 251, 'audiobooks': 68, 'true': 488, 'crime': 200, 'italian': 325, 'cherokee': 146, 'indians': 312, 'african': 24, 'men': 373, 'dent': 211, 'arthur': 58, 'brewing': 111, 'childrens': 151, 'domestic': 224, 'language': 341, 'arts': 63, 'disciplines': 220, 'law': 345, 'cats': 137, 'family': 254, 'relationships': 443, 'health': 288, 'fitness': 264, 'travel': 486, 'sports': 471, 'recreation': 438, 'abortion': 4, 'medical': 372, 'child': 149, 'psychologists': 431, 'baggins': 80, 'frodo': 274, 'audiocassettes': 69, 'brooklyn': 114, 'adventure': 21, 'intelligence': 318, 'service': 460, 'drama': 227, 'middle': 375, 'west': 495, 'brothers': 115, 'sisters': 463, 'comics': 173, 'graphic': 284, 'novels': 402, 'cities': 158, 'towns': 483, 'on': 405, 'other': 409, 'planets': 423, 'soldiers': 465, 'divorced': 222, 'women': 500, 'foreign': 266, 'study': 475, 'krynn': 339, 'abusive': 7, 'mental': 374, 'illness': 309, 'fathers': 257, 'sons': 466, 'boys': 107, 'botanists': 105, 'religion': 444, 'alienation': 31, 'psychology': 432, 'actors': 12, 'angels': 43, 'kindness': 337, 'pets': 417, 'baltimore': 82, 'maryland': 366, 'allegories': 32, 'adultery': 18, 'interpersonal': 319, 'relations': 442, 'covenant': 195, 'thomas': 481, 'new': 396, 'orleans': 407, 'la': 340, 'dragons': 226, 'english': 239, 'burglars': 118, 'anal': 41, 'sex': 461, 'darling': 207, 'jessica': 330, 'developmental': 215, 'criticism': 202, 'courts': 192, 'courtiers': 191, 'architects': 53, 'argentina': 55, 'compulsive': 177, 'eating': 233, 'accidents': 10, 'copenhagen': 185, 'denmark': 210, 'wit': 497, 'reference': 439, 'married': 365, 'people': 414, 'book': 102, 'burning': 119, 'jamaica': 328, 'cowboys': 196, 'chocolate': 153, 'creation': 198, 'artistic': 61, 'etc': 247, 'neardeath': 393, 'experiences': 250, 'amerikan': 38, 'roman': 449, 'cuilt': 203, 'house': 301, 'home': 296, 'hand': 286, 'puppets': 433, 'blake': 95, 'anita': 46, 'boarding': 97, 'schools': 455, 'alabama': 28, 'cape': 130, 'cod': 165, 'mass': 367, 'avarice': 78, 'cowgirls': 197, 'catskill': 138, 'mountains': 385, 'region': 440, 'ny': 403, 'manwoman': 363, 'amish': 39, 'materia': 368, 'medica': 371, 'jerusalem': 329, 'boston': 104, 'children': 150, 'holocaust': 295, 'survivors': 477, 'beats': 84, 'persons': 416, 'books': 103, 'reading': 437, 'bail': 81, 'bond': 100, 'agents': 25, 'art': 57, 'forgers': 268, 'large': 343, 'type': 489, 'close': 163, 'encounters': 236, 'the': 479, 'third': 480, 'kind': 336, 'motion': 384, 'picture': 421, 'bray': 110, 'nell': 394, 'bunnicula': 117, 'assertiveness': 65, 'artificial': 60, 'death': 208, 'alps': 35, 'catholic': 136, 'church': 157, 'apologetics': 51, 'belgariadbook': 87, 'mythical': 390, 'veterinarians': 491, 'dreams': 228, 'automobiles': 77, 'spouses': 472, 'coma': 172, 'in': 311, 'france': 270, 'casteel': 135, 'characters': 143, 'communication': 174, 'marriage': 364, 'assassins': 64, 'charityschools': 144, 'aircraft': 27, 'businesswomen': 122, 'performing': 415, 'amsterdam': 40, 'netherlands': 395, 'haunted': 287, 'houses': 302, 'apocalyptic': 50, 'york': 505, 'music': 388, 'trade': 484, 'human': 303, 'reproduction': 446, 'orphans': 408, 'families': 253, 'government': 283, 'investigators': 320, 'entertainers': 240, 'hispanic': 292, 'aging': 26, 'ireland': 321, 'lesbians': 348, 'devon': 216, 'war': 493, 'chicago': 147, 'ill': 308, 'canadian': 127, 'capitalism': 131, 'cancer': 128, 'behavior': 86, 'modification': 379, 'curiosities': 204, 'wonders': 501, 'corporations': 187, 'africa': 23, 'computer': 178, 'industry': 314, 'aunts': 70, 'cousins': 194, 'cornwall': 186, 'county': 189, 'louisiana': 358, 'hemophilia': 291, 'czech': 206, 'crisis': 201, 'management': 362, 'capitalists': 132, 'financiers': 263, 'bondage': 101, 'sexual': 462, 'animal': 44, 'conspiracies': 182, 'adults': 19, 'abused': 6, 'wives': 499, 'atlantic': 66, 'city': 159, 'nj': 399, 'spiritual': 470, 'princesses': 429, 'biographical': 92, 'bank': 83, 'robberies': 448, 'arabs': 52, 'austria': 73, 'christianity': 155, 'accelerated': 8, 'readers': 436, 'welfare': 494, 'police': 425, 'charleston': 145, 'sc': 454, 'paranormal': 412, 'abuse': 5, 'blessing': 96, 'cursing': 205, 'actresses': 13, 'antiques': 48, 'collectibles': 166, 'revenge': 447, 'cree': 199, 'bilbo': 89, 'horse': 299, 'racing': 434, 'earth': 232, 'depressed': 212, 'identity': 307, 'legislators': 347, 'outlaws': 411, 'world': 504, '19391945': 0, 'bullies': 116, 'chinese': 152, 'deutschland': 214, 'erwachsener': 244, '2540': 1, 'jahre': 327, 'alltagskultur': 33, 'lebensstil': 346, 'monk': 381, 'william': 496, 'town': 482, 'secrets': 458, 'north': 401, 'carolina': 133, 'french': 272, 'accident': 9, 'victims': 492, 'classical': 162, 'gardens': 276, 'murry': 387, 'babies': 79, 'prose': 430, 'classic': 161, 'pianists': 420, 'hell': 290, 'romance': 450, 'magic': 360, 'antisemitism': 49, 'long': 357, 'island': 323, 'deception': 209, 'canon': 129, 'literarature': 353, 'brain': 109, 'adoption': 16, 'israel': 324, 'presidents': 428, 'bioethics': 91, 'lovely': 359, 'story': 474, 'friendship': 273, 'cattle': 139, 'drives': 229, 'coal': 164, 'miners': 377, 'ghost': 279, 'chick': 148, 'lit': 352, 'epic': 242, 'dracula': 225, 'count': 188, 'insurance': 317, 'claims': 160, 'global': 281, 'environmental': 241, 'change': 141, 'canada': 126, 'gangs': 275, 'montana': 383, 'drugs': 230, 'jewish': 331, 'with': 498, 'disabilities': 218, 'abduction': 3, 'newbery': 397, 'medal': 370, 'frankensteins': 271, 'monster': 382, 'boulder': 106, 'colo': 169, 'girls': 280, 'homicide': 297, 'essence': 246, 'celebrities': 140, 'arthurian': 59, 'romances': 451, 'confession': 181, 'adoptees': 15, 'fansler': 255, 'kate': 334, 'hitchhiking': 294, 'indochina': 313, 'mammals': 361, 'mythology': 391, 'horses': 300, 'spanish': 468, 'materials': 369, 'call': 125, 'woodrow': 502, 'albany': 29, 'anonymous': 47, 'letters': 349, 'action': 11, 'courage': 190, 'australian': 72, 'gated': 277, 'communities': 175, '87th': 2, 'precinct': 427, 'photography': 419, 'fort': 269, 'lauderdale': 344, 'fla': 265, 'education': 235, 'black': 94, 'beauty': 85, 'kings': 338, 'rulers': 452, 'outer': 410, 'space': 467, 'idaho': 306, 'braille': 108, 'librarians': 350, 'epistolary': 243, 'inheritance': 316, 'succession': 476, 'kenya': 335, 'feminist': 258, 'austistic': 71, 'second': 457, 'advent': 20, 'alphabet': 34, 'languages': 342, 'forensic': 267, 'pathology': 413, 'fairy': 252, 'castaways': 134, 'minnesota': 378, 'beowulf': 88, 'arrakis': 56, 'disasters': 219, 'good': 282, 'evil': 249, 'infants': 315, 'newborn': 398, 'divorce': 221, 'colombia': 170, 'training': 485, 'heart': 289, 'utah': 490}

          index
fiction     260
cooking     184
history     293
humor       304
conduct     180
...         ...
divorce     221
colombia    170
training    485
heart       289
utah        490

[506 rows x 1 columns]

In [18]:
category_vecs.toarray()[:20]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
# 코사인 유사도 측정
from sklearn.metrics.pairwise import cosine_similarity

# batch차원의 배열들의 유사도 계산
category_sim = cosine_similarity(category_vecs,category_vecs)

MemoryError: Unable to allocate 16.2 GiB for an array with shape (2179563321,) and data type float64

In [209]:
# 텍스트 군집화 하기
# 카테고리 380개 -> 20개로 군집화
import re
from nltk import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

unique_category = book_filter_df['Category'].unique()
unique_category = preprocess_category(pd.Series(unique_category)).tolist()

# 벡터화
tfidf_vectorizer = TfidfVectorizer(min_df=2, max_df=0.5)
tfidf_matrix = tfidf_vectorizer.fit_transform(unique_category)

# kmeans
kmeans = KMeans(n_clusters=30, random_state=0)
kmeans.fit(tfidf_matrix)
clusters = kmeans.labels_
temp_df=pd.DataFrame({
    'cluster':clusters,
    'category':unique_category,
})

representative_genres =dict(temp_df.groupby('cluster')['category'].first())

reversed_representative_genres = {value: key for key, value in representative_genres.items()}

book_filter_df['category_clustered'] = book_filter_df['Category'].map(reversed_representative_genres)
book_filter_df
print(book_filter_df['category_clustered'].isnull().sum())

unmapped_categories = book_filter_df[book_filter_df['category_clustered'].isnull()]['Category'].unique()
print("매핑되지 않은 Category 값들:", unmapped_categories)

In [210]:
# Category 라벨인코딩

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

oo = encoder.fit_transform(book_filter_df['Category'])
oo=pd.DataFrame(oo)
oo.value_counts().sort_values()
print(encoder.classes_)

['87th precinct imaginary place' '9' 'abduction' 'abortion'
 'abused children' 'abused wives' 'abusive men' 'accelerated readers'
 'accident victims' 'accidents' 'action and adventure' 'actors'
 'adolescence' 'adoptees' 'adoption' 'adulteresses' 'adultery'
 'adventure stories' 'aerospace engineers' 'africa'
 'african american authors' 'african american girls'
 'african american men' 'african american police' 'african american women'
 'african americans' 'african fiction' 'aging' 'aircraft accidents'
 'alabama' 'albany ny' 'alchemists' 'alienation social psychology'
 'allegories' 'alphabet' 'alps' 'american fiction' 'american literature'
 'american poetry' 'american wit and humor' 'americans' 'amerikan roman'
 'amish' 'amsterdam netherlands' 'anal sex' 'angels' 'animal behavior'
 'animal training' 'animal welfare' 'animals' 'animals mythical'
 'anonymous letters' 'antiques  collectibles' 'antisemitism'
 'apocalyptic literature' 'apologetics' 'arabs' 'architects'
 'arctic regions' 'argentina' 'arrakis imaginary place' 'art'
 'art forgers' 'arthurian romances' 'artificial intelligence' 'artists'
 'artists spouses' 'assassins' 'assertiveness psychology'
 'atlantic city nj' 'atomic bomb' 'audiobooks' 'audiocassettes' 'aunts'
 'austistic children' 'australian fiction' 'austria' 'authors american'
 'authors english' 'authors french' 'automobiles' 'avarice' 'babies'
 'baggins bilbo fictitious character' 'baggins frodo fictitious character'
 'bail bond agents' 'baltimore maryland' 'bank robberies' 'beats persons'
 'behavior modification' 'belgariadbook 5' 'beowulf' 'bildungsromans'
 'bioethics' 'biographical fiction' 'biography  autobiography'
 'black beauty fictitious character' 'blake anita fictitious character'
 'blessing and cursing' 'boarding schools' 'body mind  spirit'
 'bondage sexual behavior' 'book burning' 'books and reading'
 'boston mass' 'botanists' 'boulder colo' 'boys' 'braille books' 'brain'
 'bray nell fictitious character' 'brewing' 'british'
 'british and irish fiction fictional works by one author' 'brooklyn'
 'brooklyn new york ny' 'brothers' 'brothers and sisters' 'bullies'
 'bunnicula fictitious character' 'burglars' 'business  economics'
 'businessmen' 'businesswomen' 'california'
 'call woodrow fictitious character' 'canada' 'canadian fiction'
 'canadian literature' 'cancer' 'canon literarature' 'cape cod mass'
 'capitalism' 'capitalists and financiers' 'castaways'
 'casteel family fictitious characters' 'catholic church' 'cats'
 'catskill mountains region ny' 'cattle drives' 'celebrities' 'character'
 'charityschools' 'charleston sc' 'cherokee indians' 'chicago ill'
 'chick lit' 'child abuse' 'child psychologists' 'children'
 'children and adults' 'children and war'
 'children of holocaust survivors' 'children of presidents'
 'children with disabilities' 'childrens literature'
 'childrens poetry american' 'childrens secrets' 'childrens stories'
 'childrens stories english' 'chinese american women' 'chocolate'
 'christianity' 'christmas stories' 'cities and towns'
 'city and town life' 'classic' 'classical literature'
 'close encounters of the third kind motion picture' 'coal miners'
 'colombia' 'colombian fiction' 'coma' 'comics  graphic novels'
 'communication in marriage' 'community colleges' 'compulsive eating'
 'computer industry' 'computers' 'conduct of life' 'confession'
 'conspiracies'
 'continental european fiction fictional works by one author' 'cooking'
 'copenhagen denmark' 'cornwall england  county' 'corporations' 'courage'
 'courts and courtiers' 'courtship' 'cousins'
 'covenant thomas fictitious character' 'cowboys' 'cowgirls'
 'creation literary artistic etc' 'cree indians' 'crime'
 'crisis management in government' 'cuilt' 'curiosities and wonders'
 'czech americans' 'darling jessica fictitious character' 'death'
 'deception' 'dent arthur fictitious character' 'depressed persons'
 'detective and mystery stories'
 'deutschland  erwachsener 2540 jahre  alltagskultur  lebensstil'
 'developmental psychology' 'devon england' 'diary fiction' 'disasters'
 'divorce' 'divorced women' 'dogs' 'domestic animals' 'domestic fiction'
 'dracula count fictitious character' 'dragons' 'drama' 'dreams' 'drugs'
 'dune imaginary place' 'education' 'england' 'english fiction'
 'entertainers' 'epic literature' 'epistolary fiction' 'eschatology'
 'essence philosophy' 'fairies' 'fairy tales' 'families'
 'family  relationships' 'fansler kate fictitious character' 'fantasy'
 'fantasy fiction' 'fantasy fiction english' 'fathers' 'fathers and sons'
 'feminist literature' 'feminists' 'fiction' 'fiction in english'
 'foreign language study' 'forensic pathology' 'fort lauderdale fla'
 'france' 'frankensteins monster fictitious character'
 'french prose literature' 'friendship' 'gangs' 'gardens'
 'gated communities' 'geishas' 'ghost stories american'
 'global environmental change' 'good and evil' 'government investigators'
 'great britain' 'hand puppets' 'haunted houses' 'health  fitness' 'heart'
 'hell' 'hemophilia' 'hispanic americans' 'history' 'hitchhiking'
 'holocaust jewish 19391945' 'homicide' 'horror fiction american'
 'horror stories' 'horror tales' 'horror tales american' 'horse racing'
 'horses' 'house  home' 'human reproduction' 'humor' 'humorous stories'
 'humorous stories english' 'idaho' 'identity psychology' 'indochina'
 'infants newborn' 'inheritance and succession' 'insurance claims'
 'intelligence service' 'interpersonal relations' 'ireland' 'israel'
 'italian fiction' 'jamaica' 'jerusalem' 'journalists' 'juvenile fiction'
 'juvenile nonfiction' 'kenya' 'kindness' 'kings and rulers'
 'krynn imaginary place' 'language and languages'
 'language arts  disciplines' 'large type books' 'law' 'legislators'
 'lesbians' 'librarians' 'life' 'life on other planets'
 'literary collections' 'literary criticism' 'london england'
 'long island ny' 'louisiana' 'lovely story' 'magic' 'mammals'
 'manwoman relationships' 'married people' 'materia medica' 'medical'
 'mental illness' 'middle earth imaginary place' 'middle west' 'minnesota'
 'monastic and religious life' 'monk william fictitious character'
 'montana' 'motion picture actors and actresses' 'murder'
 'murry family fictitious characters' 'music' 'music trade' 'mythology'
 'nature' 'neardeath experiences' 'new orleans la' 'newbery medal'
 'north carolina' 'orphans' 'outer space' 'outlaws' 'paranormal fiction'
 'performing arts' 'pets' 'philosophy' 'photography' 'pianists' 'poetry'
 'political science' 'princesses' 'psychology'
 'rapture christian eschatology' 'reference' 'religion' 'revenge'
 'romance fiction' 'ryan jack fictitious character' 'science'
 'science fiction' 'science fiction american' 'second advent' 'selfhelp'
 'social science' 'soldiers' 'spanish language materials' 'spiritual life'
 'sports  recreation' 'travel' 'trials murder' 'true crime' 'utah'
 'veterinarians' 'world war 19391945']

In [ ]:
#